name: jop_finder_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1
dependency_overrides:
  flutter_svg: ^2.0.9

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.0.0+2
  floating_bottom_bar: ^0.0.3
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  flutter_svg: ^1.0.3
  intl: ^0.17.0 

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  go_router: ^14.2.7
  firebase_core: ^3.6.0
  flutter_screenutil: ^5.9.3
  cloud_firestore: ^5.4.3
  file_picker: ^4.0.0
  image_picker: ^1.1.2
  firebase_storage: ^12.3.2
  firebase_auth: ^5.3.1
  url_launcher: ^6.0.12
  cached_network_image: ^3.3.1
  shared_preferences: ^2.3.1
  google_sign_in: ^6.2.1
  icons_plus: ^3.0.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        # - asset: fonts/Schyler-Italic.ttf
        #   style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
